### ISSUE TITLE
Add install of maverick-api and dependencies to maverick

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#1]

**Comment by fnoop** [comment]
https://github.com/graphql-python/graphene
https://github.com/graphql-python/graphene-sqlalchemy
https://github.com/IlyaRadinsky/tornadoql/blob/03a90888fdff2d1593767ede154729980d237ed0/setup.py

**Comment by SamuelDudley** [comment]
note that I have used the code from https://github.com/IlyaRadinsky/tornadoql, but have not installed tornadoql as per https://github.com/IlyaRadinsky/tornadoql/blob/03a90888fdff2d1593767ede154729980d237ed0/setup.py
Need to see where `rx` is being used an if it is actually needed

**Comment by fnoop** [comment]
Mostly implemented in https://github.com/goodrobots/maverick/issues/724
