### ISSUE TITLE
Param values show excessive precision

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick-api#16]
>"id": "ACRO_RP_EXPO",
"value": 0.30000001192092896

Which is actually 0.3

**Comment by SamuelDudley** [comment]
@fnoop I have submitted a fix with https://github.com/goodrobots/maverick-api/commit/2ea82d8b7f02bf007767403fbb38a094012aa76a

can you please confirm that it will work for you?

**Comment by fnoop** [comment]
Looks much better! This fixes lots of problems I was having with parameters.
