### ISSUE TITLE
Info Invalid GraphQL 'VehicleInfo' data returned from api: dev

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#204]
This happens quite a bit.  Not sure where the error is - api or web (requesting the wrong thing), but it should be a clearer error.  The error itself comes from -api, so -api should handle errors better and present a better message to the frontend, and to it's own logs.

**Comment by SamuelDudley** [comment]
![image](https://user-images.githubusercontent.com/8290680/73608310-8fdb6880-4615-11ea-897d-93b6e36f73bd.png)

The issue was / is that the python graphql library swallows the entire stack trace leaving -api with only the error message you see in the console. 

related info in #87

**Comment by SamuelDudley** [comment]
-api traceback added to both -api logs and the web front end via json https://github.com/goodrobots/maverick-api/commit/4a4aeff802599618695d68d05b6fa471b0361b76

**Comment by fnoop** [comment]
As per #39, vehicleinfo is missing from mavros topics, so it mustn't have been folded into mavros.

However -api still adds it to the available schema even if it isn't available, and so -web verifies it true and then tries to use it.

**Comment by fnoop** [comment]
Ah, we need to migrate to what vehicleinfo turned into:
https://github.com/mavlink/mavros/pull/1150
