### ISSUE TITLE
Add zeroconf broadcast of -api

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#213]
-api should announce itself on the network so clients (-web) can find it.

**Comment by SamuelDudley** [comment]
https://github.com/jstasiak/python-zeroconf/blob/master/examples/registration.py

**Comment by SamuelDudley** [comment]
@fnoop maverick-api now looks for other api and announces itself via zeroconf

**Comment by SamuelDudley** [comment]
Use `socket.getfqdn()`

**Comment by fnoop** [comment]
clashes with avahi:
```
[I 2020-03-02,10:01:13 /srv/maverick/code/maverick-api/maverick_api/modules/__init__.py:112]
    Loading module: api.status
Traceback (most recent call last):
  File "/srv/maverick/code/maverick-api/maverick-api.py", line 41, in <module>
    api.initialize()
  File "/srv/maverick/code/maverick-api/maverick_api/modules/base/apiserver/__init__.py", line 68, in initialize
    self.discovery_zeroconf_module = DiscoveryZeroconfModule(loop, module_schema)
  File "/srv/maverick/code/maverick-api/maverick_api/modules/api/discovery/discovery_zeroconf.py", line 34, in __init__
    self.zeroconf = Zeroconf(ip_version=ip_version)
  File "/srv/maverick/software/python/lib/python3.7/site-packages/zeroconf/__init__.py", line 2134, in __init__
    interfaces, unicast, ip_version, apple_p2p=apple_p2p
  File "/srv/maverick/software/python/lib/python3.7/site-packages/zeroconf/__init__.py", line 2054, in create_sockets
    listen_socket = new_socket(ip_version=ip_version, apple_p2p=apple_p2p)
  File "/srv/maverick/software/python/lib/python3.7/site-packages/zeroconf/__init__.py", line 1992, in new_socket
    s.bind(('', port))
OSError: [Errno 98] Address already in use
```

**Comment by fnoop** [comment]
Think we need to check if a zeroconf is already running or present on the network, and if so then register with it

**Comment by fnoop** [comment]
Or it's possible we can start on a different port and co-exist

**Comment by SamuelDudley** [comment]
Darn...

**Comment by fnoop** [comment]
Possible fix for clashing zeroconf stacks:
https://github.com/goodrobots/maverick/issues/912

Also note that -api is advertising with a single generic service name:
`+   eth0 IPv4 Maverick API                                  Web Site             local`
(see `avahi-browse -a`)
I think this means that -api running on multiple devices will clash.

**Comment by SamuelDudley** [comment]
Updated the name to include the -api uuid. Hopefully no clashes now :)

**Comment by SamuelDudley** [comment]
Need to add service browser support so that other -api instances and visiond can be found and sent via graphql to -web
https://github.com/jstasiak/python-zeroconf/blob/master/examples/browser.py

**Comment by fnoop** [comment]
Could you add -api ssl state to the broadcast?

**Comment by fnoop** [comment]
Could you please also add the unique id?

**Comment by SamuelDudley** [comment]
https://github.com/goodrobots/maverick-api/blob/master/maverick_api/modules/api/discovery/discovery_zeroconf.py#L32

Depending on if SSL is used the broadcast should already give the endpoints as http/https. The unique ID is in the broadcast name, do you need an line in properties with that also?

**Comment by fnoop** [comment]
I've added uuid and service_type fields to properties dict - is the uuid unique to the instance of -api?  If there are multiple -api running on the same computer will they get different uuids, and is it the same after -api is restarted?

**Comment by SamuelDudley** [comment]
It will be unique to the server, but it currently resets to a new value every boot. I need to make the uuid persistent in the -api database.

**Comment by fnoop** [comment]
Sorry when you say unique to the server, does that mean the computer server or the -api server?

Yes please to persistent - we'll need that to recognise it in the -web over time, otherwise it will keep trying to create new clients.

**Comment by SamuelDudley** [comment]
Individual ID per API instance. The plan was always

**Comment by fnoop** [comment]
uuid4 is not creating repeatable ids, so everytime the machine is rebooted -web discovers duplicate api connections.  This doesn't seem to happen with visiond, so uuid5 looks good.
