### ISSUE TITLE
add human name to configuration and serve via zeroconf

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick-api#223]
The name will be defined in config and set via maverick when a "service group" is created e.g. dev or sitl

The name can be overwritten / set to whatever the user wants but if created by maverick will be set to the name defined for the "service group". Ideally the user has the ability to set the name in localconf.

**Comment by fnoop** [comment]
As well as a name for the vehicle, would be great to also have a cluster/swarm/group name as well.  eg.
Name=DevFrame 350 v1
Group=Garage Swarm

**Comment by fnoop** [comment]
Added a 'Name' parameter to the config which will be shown if set:
`+  wman0 IPv4 maverick-api (Maverick)                       _api._tcp            local`

 If not, it will generate a name from hostname:port, for uniqueness:
`+  wman0 IPv4 maverick-api (maverick-nano:7000)             _api._tcp            local`

**Comment by fnoop** [comment]
Added in #224
