### ISSUE TITLE
API takes a long time to begin serving data over graphql

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick-api#25]
Since last night I have noticed that restarting the API causes a long delay before data resumes streaming

**Comment by fnoop** [comment]
It's possible it's some kind of timeout/retry in the apollo client in the browser.  Could be tested by loading graphiql subscription page and then mashing the play button after restarting api, to see how long it takes to respond.

**Comment by SamuelDudley** [comment]
Turns out it was blocking on a slow request to the ardupilot autotest server when retrieving meta. I have now added a timeout.
