### ISSUE TITLE
Modularise schema

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#36]
Api and Schema is all currently in a couple of big files which makes it difficult to add new modules/features.  Would be much easier if the logic for each area was broken out into separate python modules.

**Comment by SamuelDudley** [comment]
This is really important and is high on my list of things to do. Currently I think the schema and the mavros callback functionality should live together in a discreet module.

**Comment by SamuelDudley** [comment]
Generate a structure so that tornado IO loop callbacks, mavros callbacks and schema can live in one "module". For now each module will be loaded at runtime, with the plan to add module loading controls at a later date.

**Comment by SamuelDudley** [comment]
closing as the new api code has allowed this to move forward. See #55 for further work.
