### ISSUE TITLE
Deprecate graphiql in maverick-api in favour of devtools

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#41]
Leaving graphiql in the api server is an 'open book', bad practice and bad security.  Instead support and use https://github.com/apollographql/apollo-client-devtools

**Comment by SamuelDudley** [comment]
Grapiql is quite convenient for development. What are your thoughts on keeping it included if a `development` flag is set? This flag would be opt-in to make sure users are not exposed by default.

**Comment by SamuelDudley** [comment]
implemented with 38c9606f28529d805c63ff583ed726f5d823c91c
