### ISSUE TITLE
mongodb is currently required/hardcoded

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#49]
mongodb support is currently required and the db_client created in the main script is passed through settings as an object.

Should support be optional?
Regardless I think passing the client object should happen outside of settings (and must with the new tornado options model).

**Comment by fnoop** [comment]
We could subclass mongodb support and create other subclasses like ldap/sqlite, and fall back to sqlite if ldap/mongodb not supported (assuming we can do whatever is necessary in sqlite).
Sqlite is the lightest, simplest and most universally available option.

**Comment by SamuelDudley** [comment]
Agreed

**Comment by SamuelDudley** [comment]
Subclassed and moved to tinydb by default.
