### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#54]
Need to document the gql api for endpoints to use (ie what messages and schema are available, field types etc).
Possible to autogenerate the docs?

**Comment by SamuelDudley** [comment]
Some options

https://github.com/gjtorikian/graphql-docs/blob/master/README.md

https://github.com/2fd/graphdoc

Doesn't seem to be a python version out there yet.

It would be great to go one step further and show what endpoints require auth and at what level.

**Comment by SamuelDudley** [comment]
Looks like drone deploy is using https://github.com/2fd/graphdoc#readme

**Comment by SamuelDudley** [comment]
docs are now being built as a github action https://github.com/goodrobots/maverick-api/commit/ede434f186281fc02579a4b45e3197ad62a65c4d

https://goodrobots.github.io/maverick-api/

Note that the docs are not great... need to look into other options. Seems like drone deploy has a private fork of https://github.com/2fd/graphdoc and is generating the documentation from there (much nicer).

For now its better than nothing...

**Comment by fnoop** [comment]
Looks good!  Is all the mavros related stuff missing because the modules are disabled?

**Comment by SamuelDudley** [comment]
Correct. The schema is built as the modules are loaded and as mavros is disabled the schema is missing.

**Comment by fnoop** [comment]
Can you build the schema for all modules instead?  I would have thought for public docs we would want all possibly modules documented?

**Comment by SamuelDudley** [comment]
@fnoop see https://github.com/goodrobots/maverick-api/issues/208
