### ISSUE TITLE
should param parse scripts still be standalone?

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#62]
parse_param_xml.py and PX4_parse_param_xml.py are standalone python2 scripts.  They are primarily called as modules - can we remove __main__ supporting code?

**Comment by SamuelDudley** [comment]
While it think it doesn't hurt to have a simple example usage in __main__ the code that is there is really only from my debugging and should be removed to be replaced by a test suite.

**Comment by SamuelDudley** [comment]
Stand alone `__main__` code removed. Cleanup and test suite required.
