### ISSUE TITLE
log directory created relative to cwd

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#65]
logs directory seems to be created relative to current directory of calling shell, rather than relative to basedir.

**Comment by fnoop** [comment]
On the other hand, if we force it relative to the basedir then can we specify absolute path?

**Comment by SamuelDudley** [comment]
I'll make some changes in a pr and you can tell me what you think

**Comment by fnoop** [comment]
I think this is fine as it is, to create log directory relative to calling path, so we can specify log path in config file for multiple instances, related to #69.  Need to raise similar issue to support configurable data path.
