### ISSUE TITLE
gql status field format

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#68]
status message currently has:
  currentTime
  currentStatus

but the other mavros messages fields have been renamed from camelCase to underscored, so status fields would be:
 current_time
 current_status

We should keep consistent, whatever the format

**Comment by SamuelDudley** [comment]
Graphene auto camelCase'd from snake_case where as graphql-core-next seems to pass the variable name without modification. What would you prefer in the client side?

**Comment by fnoop** [comment]
Don't mind - I prefer camelCase personally, I think it looks better and is easier to deal with, but don't mind.

**Comment by SamuelDudley** [comment]
fixed with https://github.com/goodrobots/maverick-api/commit/cd20dca66c1793c8ba3b4695366c58d1774a5825
