### ISSUE TITLE
Query parameters not working

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#75]
Not sure where the problem is - could well be the client - but I think it's formulating the query correctly.  api.log shows:

```
[D 2019-01-11,07:35:17 /srv/maverick/code/maverick-api/maverick_api/modules/base/tornadoql/graphql_handler.py:95]
    GraphQL result data: None errors: [GraphQLError("Variable '$id' of required type 'String!' was not provided.", locations=[SourceLocation(line=1, column=24)])]
[W 2019-01-11,07:35:17 /srv/maverick/code/maverick-api/maverick_api/modules/base/tornadoql/graphql_handler.py:101]
    GraphQL Error: Variable '$id' of required type 'String!' was not provided.

    GraphQL request (1:24)
    1: query missionListQuery($id: String!) {
                              ^
    2:   MissionList(id: $id) {
```

Chrome shows the query variables being sent:
<img width="681" alt="screenshot 2019-01-11 at 08 48 30" src="https://user-images.githubusercontent.com/8210968/51023018-b7c8db80-157d-11e9-8fb1-045b2a40e983.png">

**Comment by SamuelDudley** [comment]
Most likely API side... I dont think im passing the `variables` field into the query. I'll have a look.

**Comment by SamuelDudley** [comment]
Fixed by https://github.com/goodrobots/maverick-api/commit/7dc7529a4ce7a2d60f9d52ff1d178f1131f9d7a2

@fnoop Can you confirm?

**Comment by fnoop** [comment]
Fixed, thanks!
